"""empty message

Revision ID: 0a91fb858408
Revises: 4856469a364f
Create Date: 2020-10-24 15:17:34.847313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a91fb858408'
down_revision = '4856469a364f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
