"""empty message

Revision ID: 4856469a364f
Revises: cf2c826e25be
Create Date: 2020-10-24 15:12:21.971625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4856469a364f'
down_revision = 'cf2c826e25be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
