"""empty message

Revision ID: 4ff1a2cb60c0
Revises: 88de3fba4b96
Create Date: 2020-10-24 15:27:25.361171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff1a2cb60c0'
down_revision = '88de3fba4b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
