"""empty message

Revision ID: 88de3fba4b96
Revises: 0a91fb858408
Create Date: 2020-10-24 15:27:06.106894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88de3fba4b96'
down_revision = '0a91fb858408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
