"""empty message

Revision ID: cf2c826e25be
Revises: e415a1abf870
Create Date: 2020-10-24 15:06:32.814855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2c826e25be'
down_revision = 'e415a1abf870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
